### ISSUE TITLE
Feature: use avatar from github/google

### ISSUE THREAD

**Issue by gerboland** [PythonIreland/broadgauge#2]
There are several places in the site where a blank "user" image is used:
- each trainers page
- list of trainers page Would be cool to replace this generic image with the user's github avatar/google/gravatar image if available.

**Comment by edgarlatorre** [comment]
working on this one

**Comment by mariusavram91** [comment]
also working on it

**Comment by andrewmccarthy** [comment]
Pull requests #40 and #41 seem to fix this. Ticket can be closed.

**Comment by andreafagan** [comment]
Thanks
