### ISSUE TITLE
Workshop description field supports markdown, should add small hint above text box to state this facy

### ISSUE THREAD

**Issue by gerboland** [PythonIreland/broadgauge#42]
Workshop descriptions can be entered with the Markdown syntax [1], to format the description in a pleasant way. But there is no hint to the user that this is the case. 

Would be good to add small text hint to user that markdown is supported for that text entry box..

[1] http://daringfireball.net/projects/markdown/syntax

**Comment by andrewmccarthy** [comment]
Will do this
